name: alarmdar
description: Alarms & Reminders

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ui dependencies
  cupertino_icons: ^1.0.3
  fluttertoast: ^8.0.8

  #database dependencies
  sembast: ^3.1.1
  path_provider: ^2.0.5

  #notifications dependencies
  flutter_local_notifications: ^8.1.1+1

  # misc
  intl: ^0.17.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true